___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [4]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [9]:
np.array((5,5,5,5,5,5,5,5,5,5,5))

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [11]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [15]:
a = [int(i) for i in range(10,50) if i%2==0]
b = np.array(a)
b

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [25]:
l = [[1,0,0],[0,1,0],[0,0,1]]
b = np.array(l)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### Use NumPy to generate a random number between 0 and 1

In [31]:
from numpy import random
random.randint(0,1)

0

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [32]:
np.random.normal(0,1,25)

array([-0.21815053,  0.26033929,  0.56606085, -0.41052098,  0.51474669,
       -0.83035439, -1.23221475, -1.52106117, -0.48231074,  0.40429242,
        0.00705041,  0.1472917 , -0.02636389, -0.36628397,  1.32323352,
       -0.26444795, -1.61361111, -1.1156603 ,  0.89896324,  0.27983466,
       -0.04166975, -0.19659818, -2.40882426,  3.1540535 , -0.38135624])

#### Create the following matrix:

In [37]:
a = [i+1/100 for i in range(100)]
np.array(a)

array([1.000e-02, 1.010e+00, 2.010e+00, 3.010e+00, 4.010e+00, 5.010e+00,
       6.010e+00, 7.010e+00, 8.010e+00, 9.010e+00, 1.001e+01, 1.101e+01,
       1.201e+01, 1.301e+01, 1.401e+01, 1.501e+01, 1.601e+01, 1.701e+01,
       1.801e+01, 1.901e+01, 2.001e+01, 2.101e+01, 2.201e+01, 2.301e+01,
       2.401e+01, 2.501e+01, 2.601e+01, 2.701e+01, 2.801e+01, 2.901e+01,
       3.001e+01, 3.101e+01, 3.201e+01, 3.301e+01, 3.401e+01, 3.501e+01,
       3.601e+01, 3.701e+01, 3.801e+01, 3.901e+01, 4.001e+01, 4.101e+01,
       4.201e+01, 4.301e+01, 4.401e+01, 4.501e+01, 4.601e+01, 4.701e+01,
       4.801e+01, 4.901e+01, 5.001e+01, 5.101e+01, 5.201e+01, 5.301e+01,
       5.401e+01, 5.501e+01, 5.601e+01, 5.701e+01, 5.801e+01, 5.901e+01,
       6.001e+01, 6.101e+01, 6.201e+01, 6.301e+01, 6.401e+01, 6.501e+01,
       6.601e+01, 6.701e+01, 6.801e+01, 6.901e+01, 7.001e+01, 7.101e+01,
       7.201e+01, 7.301e+01, 7.401e+01, 7.501e+01, 7.601e+01, 7.701e+01,
       7.801e+01, 7.901e+01, 8.001e+01, 8.101e+01, 

#### Create an array of 20 linearly spaced points between 0 and 1:

In [44]:
a = [float(i)+0.05263158 for i in range(20)]
np.array(a)

array([ 0.05263158,  1.05263158,  2.05263158,  3.05263158,  4.05263158,
        5.05263158,  6.05263158,  7.05263158,  8.05263158,  9.05263158,
       10.05263158, 11.05263158, 12.05263158, 13.05263158, 14.05263158,
       15.05263158, 16.05263158, 17.05263158, 18.05263158, 19.05263158])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [29]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
mat = [[12,13,14,15],[17,18,19,20],[22,23,24,25]]

In [46]:
mat

[[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]]

In [47]:
print(20)

20


In [48]:
print(20)

20


In [51]:
mat = [[2],[7],[12]]
mat

[[2], [7], [12]]

In [53]:
np.array((21,22,23,24,25))

array([21, 22, 23, 24, 25])

In [54]:
np.array((21,22,23,24,25))

array([21, 22, 23, 24, 25])

In [59]:
mat = [[16,17,18,19,20],[21,22,23,24,25]]
np.array(mat)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [81]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [82]:
mat.std()

7.2111025509279782

#### Get the sum of all the columns in mat

In [84]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Great Job!